import turtle
import numpy as np
def okruznost(r):
    a= 2*r*np.sin(2.5*np.pi/180)
    for i in range(72):
        turtle.forward(a)
        turtle.right(5)
def poluokruznost(r):
    a= 2*r*np.sin(2.5*np.pi/180)
    for i in range(36):
        turtle.forward(a)
        turtle.right(5)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.speed(10)
turtle.shape('turtle')
turtle.left(90)
turtle.penup()
turtle.forward(100)
turtle.right(90)
turtle.pendown()
turtle.begin_fill()
okruznost(100)
turtle.color('yellow')
turtle.end_fill()
turtle.color('black')
turtle.penup()
turtle.goto(-40,60)
turtle.pendown()
turtle.begin_fill()
okruznost(20)
turtle.color('blue')
turtle.end_fill()
turtle.color('black')
turtle.penup()
turtle.goto(40,60)
turtle.pendown()
turtle.begin_fill()
okruznost(20)
turtle.color('blue')
turtle.end_fill()
turtle.color('black')
turtle.penup()
turtle.goto(0,30)
turtle.pendown()
turtle.color('brown')
turtle.width(15)
turtle.right(90)
turtle.forward(30)
turtle.color('red')
turtle.penup()
turtle.goto(40,-40)
turtle.pendown()
poluokruznost(40)